### ISSUE TITLE
{sketch_path} seems to be depreciated

### ISSUE THREAD

**Issue by a7hybnj2** [SpenceKonde/megaTinyCore#973] opened 2023-06-14 13:41 UTC
```
megaTinyCore:megaavr 2.6.8
arduino-cli  Version: 0.33.0 Commit: ca60d4b4 Date: 2023-05-29T15:18:18Z
```
I am specifying an --output-dir and it is trying to find a location that doesn't exist:

```
arduino-cli compile --fqbn megaTinyCore:megaavr:atxy6:chip=3216,clock=20internal,millis=enabled,startuptime=8,bodvoltage=1v8,bodmode=di
sabled,eesave=enable,resetpin=UPDI,printf=default,wiremode=mors,WDTtimeout=disabled,attach=allenabled --output-dir ./build
Sketch uses 1822 bytes (5%) of program storage space. Maximum is 32768 bytes.
Global variables use 155 bytes (7%) of dynamic memory, leaving 1893 bytes for local variables. Maximum is 2048 bytes.
cp: {sketch_path}/3216Blink.ino.t3216.20c0.mD0.v268.lst: No such file or directory
```

https://github.com/SpenceKonde/megaTinyCore/blob/9202a743943c4613ed08d63e9bcc47cbbbdf420a/megaavr/platform.txt#LL137C1-L145C135

I have scrubbed through the arduino-cli backend and don't see anything pointing to `{sketch_path}` maybe it is supposed to be `{build.source.path}`

Looks like it was mentioned once or twice [Like Here](https://arduino.github.io/arduino-cli/0.21/rpc/commands/#cc/arduino/cli/commands/v1/board.proto) but I don't see it...

[Also, this persons problem](https://forum.arduino.cc/t/the-file-sketch-path-after-arduin-cli/1130719)
[And, my other problem. Which includes this problem](https://github.com/MCUdude/MightyCore/issues/276#issuecomment-1588452043)

**Comment by SpenceKonde** [comment] 2023-06-14 18:29
No confirmation that this behavior was intended. They seem to jhave just broken a pretty basic part of the IDE .

**Comment by a7hybnj2** [comment] 2023-06-14 23:23
Hey, thanks for the data. I just tried multiple versions of the Arduino-cli to determine where it broke.

Looks like <=0.31.0 is okay but anything newer is all broken. I don't know exactly what is going on or why but I guess I will just use version 0.31.0 until I know they have it figured out.

Thanks for taking a look. I don't know if you want to in the installation notes put a disclaimer about not using arduino-cli > 0.31.0 but I will let you close this issue when you read this as I guess that is all that can be done.

**Comment by a7hybnj2** [comment] 2023-06-14 23:54
Thanks to IRC#arduino:

`well, it kind of looks like prior to 32 the recipe.hooks.savehex.presavehex. are not run at all.`
https://github.com/arduino/arduino-cli/compare/0.31.0..0.32.0#diff-3f49374ea3ccca90f66635310e4bfb40a4aa48a800fdcba1ec704f51d25cd1e1L253-L289
Which would explain why the with_bootloader.hex file isn't being deleted and the {sketch_path} isn't getting evaluated.

**Comment by SpenceKonde** [comment] 2023-06-25 19:44
Closing this as not actionable at this time, the issues list is my action item list

**Closed** 2023-06-25 19:44 UTC
Labels: Not our bug

**Comment by per1234** [comment] 2023-09-27 02:57
This bug is now tracked by the Arduino CLI developers at https://github.com/arduino/arduino-cli/issues/2340. There is no need to comment there. I'm only adding this comment to notify affected users that there is a formal bug report about it in the appropriate issue tracker.
