### ISSUE TITLE
Logic and Comparator libraries cannot be used together

### ISSUE THREAD

**Issue by TechAUmNu** [SpenceKonde/megaTinyCore#722] opened 2022-06-05 18:14 UTC
Logic and Comparator libraries both define a bunch of namespaces in their .h that have the same name. They should be prefixed to stop the conflict.

**Comment by SpenceKonde** [comment] 2022-06-06 00:42
This i a duplicate of https://github.com/SpenceKonde/DxCore/issues/279

I am unsure how to correctly resolve it without introducing breaking changes - I am not comfortable with namespaces and the ++ part of C++ in general and have, in that issue, asked @mcudude who created those libraries how to fix it. We can't prefix them because that will trash any existing code!

**Comment by SpenceKonde** [comment] 2022-06-06 17:13
Adding blocked label because cannot fix without advise from someone more knowledabkle about C++

**Comment by SpenceKonde** [comment] 2022-06-19 10:58
@MCUdude  - this is another super critical problem, I've had at least three people complaining about it. If you could suggest a fix especially if it didn't break existing code, that  would be really helpful. I don't see any solution that won't break all existing code that uses Comparator, Logic, or ZCD (because IIRC that also names output the same.

**Comment by MCUdude** [comment] 2022-06-19 11:10
>  If you could suggest a fix especially if it didn't break existing code, that would be really helpful.

I already have!

**Comment by SpenceKonde** [comment] 2022-07-23 20:58
Changes checked into Logic, Event and Comparator

**Closed by SpenceKonde** 2022-07-23 20:58 UTC
Labels: bug
