### ISSUE TITLE
Micronucleus certificate has expired, so installation fails

### ISSUE THREAD

**Issue by dpharris** [SpenceKonde/megaTinyCore#1124] opened 2024-07-08 04:11 UTC
Failed to install platform: 'ATTinyCore:1.5.2'. 2 UNKNOWN: Get "https://azduino.com/bin/micronucleus/micronucleus-cli-2.5-azd1-x86_64-apple-darwin.tar.bz2": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: “azduino.com” certificate is expired

This stops the installation.  Is there a workaround?  

Thx

**Comment by hmeijdam** [comment] 2024-07-08 05:31
Yes,, you can find the workaround by looking through the list of existing issues. certificate has expired has been mentioned a few times in the past months.

**Comment by dpharris** [comment] 2024-07-08 05:58
Yes, I did the work around for the expired certificate for the core, but
this is a different expired certificate.

**Comment by dpharris** [comment] 2024-07-08 06:02
I have downloaded the Micronucleus -- where do I put it?

**Comment by dpharris** [comment] 2024-07-08 06:06
Ah --- using "https://archive.org/download/azduino_micronucleus-mirror/package_drazzy.com_index.json" in the Additional boards URL worked the charm.

**Comment by hmeijdam** [comment] 2024-07-08 20:11
Creative workaround :-)

**Comment by SpenceKonde** [comment] 2024-07-26 16:20
Duplicate of issue relating to SSL. Certs renewed.

**Closed by SpenceKonde** 2024-07-26 16:20 UTC
